data:
 build: jenkins-data

master:
  build: jenkins-master
  volumes:
    - .:/backup
  volumes_from:
    - data
  ports:
    - "50000:50000"

nginx:
  build: jenkins-nginx
  ports:
    - "${HTTP_PORT}:80"
  links:
    - master:jenkins-master
