data:
 build: jenkins-data

master:
  build: jenkins-master
  volumes:
    - .:/backup
  volumes_from:
    - data
  ports:
    - "50000:50000"

nginx:
  build: jenkins-nginx
  ports:
    - "8081:80" # Need to make this configurable, as we'll want 80:80 in 'prod' environments
  links:
    - master:jenkins-master
